[project]
name = "in3190"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cartopy>=0.25.0",
    "geopy>=2.4.1",
    "h5py>=3.14.0",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "obspy>=1.4.2",
    "obspyh5>=0.6.0",
    "pandas>=2.3.2",
    "pykdtree>=1.4.3",
    "pyproj>=3.7.2",
    "pytest>=8.4.1",
    "scipy>=1.16.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["*"] # Default
